### ISSUE TITLE
Implementar um banco de dados na api

### ISSUE THREAD

**Issue by Nick-Gabe** [Nick-Gabe/nick-tech-posts#46]
### Descrição da sugestão

Atualmente os posts estão sendo salvos num json e para adicioná-los é feito um workflow, entretanto isso querendo ou não limita demais o processo, e tendo uma api com banco de dados seria possível até mesmo de fazer esse processo pelo front end.

O banco de dados a ser utilizado ainda está sendo pensado, aceito sugestões.
Essa issue por enquanto é mais uma discussão, eu pretendo manter a api serverless por enquanto, mas caso escale bastante será melhor individualizar.

### Como implementar?

A discutir*

**Comment by vboechat** [comment]
O banco de dados em questão poderia ser o Postgres, uma vez que o Vercel possui suporte nativo para essa DB através do seu serviço "Vercel Storage". Para contas com plano gratuito, possui alguns limites que podem ser levados em consideração:

- Possui limite de dados escritos de 256MB.
- Tempo de computação de máximo 60h (Resetado mensalmente).
- Transferência de dados de 256MB (Acredito que também seja resetado mensalmente).

Diante disso, para o projeto desse tamanho, acredito que esse serviço seja excelente, principalmente por possuir um armazenamento bom e suficiente para o projeto e ser um serviço da própria Vercel, de onde o projeto está hospedado.

**Comment by Nick-Gabe** [comment]
É uma boa opção sim, não tinha considerado o Postgres, vou pesquisar mais sobre!

**Comment by Nick-Gabe** [comment]
Por enquanto, vou manter o json como db temporária, mas conforme a aplicação escalar e houver uma necessidade maior eu vou reabrir este bug.
Todos os comentários serão considerados.
