### ISSUE TITLE
Separar contribuição do resto do README

### ISSUE THREAD

**Issue by Nick-Gabe** [Nick-Gabe/nick-tech-posts#53]
### Descrição da sugestão

Acho que seria uma boa deixar as infos de contribuição, como rodar o projeto, em um arquivo separado.
Pois nem todos os usuários querem ver essa parte, então poderiamos apenas linkar isso no README.

### Como implementar?

- Criar arquivo CONTRIBUTING.md
- Colocar info do "como rodar" dentro dele
- Adicionar também outros tópicos sobre como "criar um Pull Request" e "como criar uma Issue"
- No README, trocar a seção "como rodar" para "gostaria de contribuir?", e no conteúdo há um link escrito "Clique aqui para ler as informações sobre como rodar o projeto e mandar uma contribuição." que te redireciona para o arquivo CONTRIBUTING.md

**Comment by vboechat** [comment]
Não seria melhor o arquivo ser chamado de "CONTRIBUTING", como recomendado pelo GitHub para definir orientações de contribuições em um repositório?

Source: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#about-contributing-guidelines

**Comment by Nick-Gabe** [comment]
Boaa! foi erro meu hahaha, era justamente isso que eu tinha em mente sim! Valeu @vboechat!!
