### ISSUE TITLE
Será que vale a pena remover a feature de regex?

### ISSUE THREAD

**Issue by Nick-Gabe** [Nick-Gabe/nick-tech-posts#58]
### Descrição da sugestão

Atualmente ela anda dando mais dores do que utilidade, e estou achando que não vale tanto a pena. Principalmente por não ser algo tão utilizado. Além de que complica principalmente para o highlight de texto do front e filtragem de dados do back. (além do #56)

Mas eu não curto a ideia de coisas literais, acho que fica específico demais, talvez uma [fuzzy search](https://www.techtarget.com/whatis/resources) faça mais sentido? O que acham?

Aceito outras sugestões ou opiniões sobre a descrita acima 😃 

### Como implementar?

- Remover regex do front
- Remover regex do back

**Comment by Nick-Gabe** [comment]
@vboechat @YuriSamp me ajudem nessa dúvida aqui ❤️

**Comment by YuriSamp** [comment]
eu sei que acaba saindo um pouco do objetivo da issue nick mas eu como usuário me sentiria mais confortavel em ter tags tipo react, programção, curiosidades e a gente procura por elas em vez da descrição

**Comment by Nick-Gabe** [comment]
que nada, é uma ótima sugestão!
e eu pessoalmente também curto a ideia, mas como eu adicionaria tags ao fazer o fetch dos tweets?

- elas iam vir baseadas nas # do tweet? acho que ia poluir demais se tivesse mts assuntos no mesmo tweet
- palavras chave? acho que pode até ser, tipo verificar se tal texto contém react e caso sim adicionar a tag "react". além de que esse é mais retrocompatível, já que só um script e já dá pra atualizar todo o json

é uma boa honestamente, daria pra se orientar mais facilmente, aí seria só adicionar um select pra tags
então daria pra deixar a pesquisa sem fuzzy search nem regex e focar só nisso

**Comment by YuriSamp** [comment]
acho que a segunda opção é mais limpa e mais fácil de implementar, inclusive eu pensei nela

**Comment by vboechat** [comment]
Podemos utilizar a ideia do @YuriSamp e ligar essa issue com a issue #46:
Pode ser feito uma relação many-to-many entre 2 tabelas: Tags e Posts (Acredito que como é M-TO-M, seria necessário uma tabela de ligação), cada linha na tabela posts, deverá ter uma coluna de ligação, que será utilizada para ligar várias tags para uma mesma postagem, acho que seria até melhor implementar esse sistema de tags junto com uma DB do que direto no JSON, inclusive para manutenção acredito que ficaria melhor

Tabela Tags: id, tag_title, tag_description
Tabela Posts: id, title, description, link, etc
Tabela PostsAndTags: id, post_id, tag_id (Para a relação many-to-many)

**Comment by Nick-Gabe** [comment]
Ótimas sugestões pessoal, agradeço pela ajuda nessa decisão!
A feature de regex realmente vai ser removida e substituída por tags então.
