### ISSUE TITLE
Erro de escrita na template de sugestão de funcionalidade

### ISSUE THREAD

**Issue by falcao-g** [Nick-Gabe/nick-tech-posts#63]
### Descrição do problema

a descrição do campo de mídia para as issues de sugestão de features parece estar escrita errada, está escrito "Screenshot, vídeo, GIF, dentre outros, que mostrem o problema", só que esse tipo de issue é para sugerir uma nova funcionalidade, e não reportar um erro

### Como reproduzir?

veja a seção de mídia

### Comportamento esperado

imagino que seria mais interessante estar escrito algo como "Screenshot, vídeo, GIF, dentre outros, que ajudem a demonstrar a sugestão.", assim elimina o risco do usuário criando a issue achar que está fazendo algo errado

### Mídia, se aplicável

![image](https://github.com/Nick-Gabe/central-nickgabe/assets/60127788/1fd788fc-2dbc-496f-b5a7-b9448f980d9c)

**Comment by Nick-Gabe** [comment]
Mandou bem! nem tinha notado esse detalhezinho 😁
